#! /usr/bin/env python
# -*- coding:utf-8 -*-
# 便于快速识别，每个实例只有1到2个指纹信息
banner_reg = {
    # Web应用,html字段,info字段  []或条件  [[]]与条件
    "app":{"discuz":["Powered by Discuz!","Comsenz UI Team"],
           "Amiro.CMS":["-= Amiro.CMS (c) =-"],
           "Anchor CMS":['content="Anchor CMS"'],
           "Hadoop":["Hadoop Administration","Hadoop IPC port","NeMIS Hadoop Cluster Access","X-Hue-Jframe-Path:"],
           "Fortinet FortiGate":[["Content-Length: 79",'top.location="/login";'],"WWW-Authenticate: Fortigate","Powered By Fortinet"],
           "FortiWeb":['FortiWeb'],
           "Cisco Firewall":["cisco-IOS","/+CSCOE+/logon.html"],
           "Cisco modem":[["Content-Length: 1469",'window.location.href = "Docsis_system.asp";']],
           "Cisco-ACE":['<link href="/utility/cuesStylesLogo.css" rel="stylesheet" type="text/css" />'],
           "Cisco-Adaptive-Security-Appliance":['<title>Cisco Systems, Inc. Network Access</title>'],
           "Cisco-VPN":["<title>Cisco Systems, Inc. VPN 3000 Concentrator"],
           "Citrix-Access-Gateway":['<link rel="SHORTCUT ICON" href="/vpn/images/AccessGateway.ico" type="image/vnd.microsoft.icon">','Citrix Access Gateway'],
           "Citrix-Metaframe":['window.location="/Citrix/MetaFrame','MetaFrame Presentation Server Log In'],
           "Citrix-XenServer":['XenServer'],
           "DedeCMS":["DedeAjax\(","DedeCMS"],
           "Dotclear":['href="dotclear/index.php"','<p>Powered by <a href="http://dotclear.org/">Dotclear</a></p>'],
           "Drupal":['jQuery.extend\(Drupal.settings','X-Generator:Drupal'],
           "WordPress":['content="WordPress',"wp-includes"],
           "phpMyAdmin":["pma_password","<title>phpMyAdmin</title>"],
           "SeaCMS":["Powered by SeaCms","海洋CMS"],
           "FineCMS":["Powered by FineCMS","dayrui@gmail.com"],
           "ASPCMS":["ASPCMS"],
           "CmsEasy":["CmsEasy"],
           "MetInfo":['content="MetInfo',"/images/css/metinfo.css"],
           "Juniper":["Log In - Juniper Web Device","Juniper Networks, Inc."],
           "Netscreen":["Virata-EmWeb"],
           "Check-Point-Firewall":["Checkpoint Dashboard","/FW-1 at",'<meta name="description" content="Webui Login Page"/>'],
           "H3C router":["H3C-Miniware-Webs"],
           "H3C switch":["Server: Switch","Server: Lanswitch"],
           "Tplink":["tplink","TPLINK"],
           "Sangfor firewall":["SANGFOR | NGAF"],
           "DVR":["Server:Cross Web Server"],
           "SCADA":["WindRiver-WebServer"],
           "phpwind":['content="(phpwind)','content="(PHPWind)'],
           "zblog":[['<link rel="stylesheet" rev="stylesheet"','zb_users']],
           "emlog":["include/lib/js/common_tpl.js","Powered by emlog"],
           "phpcms":['<link href="templates/default/skins/default/phpcms.css',"Powered by Phpcms"],
           "dokuwiki":['content="DokuWiki', "/lib/exe/css.php"],
           "hdwiki":["Powered by HDWiki!","style/default/hdwiki.css"],
           "mediawiki":["opensearch_desc.php",'content="MediaWiki'],
           "php168":["/images/default/inc.js","/images/default/default.js","/images/default/swfobject.js"],
           "drupal":["drupal.js", 'Powered by <a href="http://drupal.org">Drupal</a>'],
           "joomla":["/media/system/js", 'Powered by <a href="http://www.joomla.org">Joomla', "Joomla! Forum"],
           "cmseasy":["Powered by CmsEasy", 'content="CmsEasy'],
           "vbulletin":["Powered by vBulletin", 'content="vBulletin'],
           "ecshop":["Powered by ECShop", 'content="ECSHOP', "/api/cron.php"],
           "shopex":['content="ShopEx'],
           "empirecms":["Powered by EmpireCMS"],
           "metinfo":["Powered by MetInfo", 'content="MetInfo', "powered_by_metinfo"],
           "foosun":["Created by DotNetCMS", "For Foosun"],
           "cmstop":["/css/cmstop-common.css", "cmstop-list-text.css", '<a class="poweredby" href="http://www.cmstop.com'],
           "jeecms":["Powered by JEECMS", "http://www.jeecms.com"],
           "espcms":["Powered by ESPCMS", "/templates/default/style/tempates_div.css"],
           "startbbs":['class="startbbs'],
           "74cms":["74cms.com", 'Powered by <a href="http://www.74cms.com/'],
           "waikucms":["Powered by <b>WaiKuCms"],
           "08cms":["cms08flash.js","js/floatwin.js"],
           "gxcms":["views/js/history.js"],
           "kesioncms":["/ks_inc/ajax.js","/ks_inc/stm"],
           "thinksaas":["ThinkSAAS", "@thinksaas.cn"],
           "douphp":["images/slide_show.js","images/global.js"],
           "discourse":['Powered by <a href="http://www.discourse.org">', "github.com/discourse/discourse version"],
           "fluxbb":['<body id="fluxbb">', 'Powered by <a href="http://fluxbb.org/">FluxBB</a>'],
           "phpbb":['Powered by <a href="http://www.phpbb.com/">phpBB', "phpBB style name: CFStyle"],
           "vanilla":["vanilla/js/discussions.js", '<body id="vanilla_'],
           "cosmoshop":["cosmoshop_functions.js","cosmoshop_formlib.js"],
           "opencart":['Powered By <a href="http://www.opencart.com">OpenCart',"/catalog/view/javascript/common.js"],
           "oscommerce":["osCommerce</a><br>Powered by", 'class="infoBoxContents">'],
           "bugzilla":["enter_bug.cgi", 'action="buglist.cgi'],
           "redmine":["Redmine", "/redmine_"],
           "struts2":["Struts Problem Report<"],
           "1024-CMS":["Powered by 1024 CMS",'content="1024 CMS (c) 2008 Treble Designs.'],
           "3dcart":["<!--START: 3dcart stats-->"],
           "AP Router":['<frame marginwidth="5" marginheight="5" src="menu_empty.html" name="menu" noresize scrolling="auto" frameborder="0">'],
           "Artiphp-CMS":['<!--  fin ArtiMenu horizontal -->','<!--  Fin ArtiMenu horizontal -->'],
           "ASP-Nuke":['<meta name="Generator" CONTENT="ASP-Nuke"'],
           "Atmail-WebMail":["<title>Acceder a UOWebmail</title>","Powered by Atmail Webmail"],
           "Atomic-CMS":["Powered by AtomicCms"],
           "AxCMS.net":["powered by Axinom"],
           "Axis Commerce":["Powered by Axis","Login to Axis administrator panel"],
           "Axis-Network-Camera":["AXIS Video Server"],
           "b2evolution":["Powered by b2evolution"],
           "Battle-Blog":["<title>Battle Blog Login</title>",'<form name = "UserInfoCollect" action = "authenticate.asp" method = "post">'],
           "Brother printer":['<FRAME SRC="/printer/inc_head.html'],
           "Barracuda-Spam-Firewall":["Barracuda Spam & Virus Firewall: Welcome"],
           "Barracuda-Waf":['<div style="border: 3px solid #4991C5; font:1.5em; font-family:tahoma,calibri,arial; font-weight:bold; color:#0A4369; padding:5px; margin:10px; text-align:center"> The requested service is temporarily unavailable. It is either overloaded or under maintenance. Please try later.</div><!--01234567890123456789'],
           "BinarySec-Firewall":["X-BinarySEC-Via header","X-BinarySEC-NoCache header"],
           "bitweaver":["Powered by bitweaver"],
           "CafeEngine":["CafeEngine</a>"],
           "Canon-Network-Camera":["Network Camera VB-C50i/VB-C50iR"],
           "chillyCMS":['powered by <a href="http://FrozenPepper.de">chillyCMS</a>'],
           "CitusCMS":["<title>Administration &#149; Webseitenname</title>","Powered by CitusCMS"],
           "CMSimple":['<meta name="generator" content="CMSimple'],
           "Constructr-CMS":["Constructr CMS"],
           "cPanel":["<title>cPanel&reg;</title>",'<img src="sys_cpanel/images/powered_by.gif" />'],
           "CruxCMS":["Created by CruxCMS"],
           "Dada-Mail":["Powered by Dada Mail"],
           "DD-WRT":['href="style/pwc/ddwrt.css"','<a href="http://www.dd-wrt.com/">DD-WRT</a>'],
           "Dell-KACE-Appliance":["x-dellkace","x-kbox"],
           "Dell-Printer":["Dell Laser Printer"],
           "Direct-Packet-Device":['<td height="30" class="login"><b><font color="ffffff" size="2" face="Arial, Helvetica, sans-serif">Password</font></b></td>'],
           "D-Link-Network-Camera":["<title>DCS-"],
           "D-LINK-router":["D-LINK"],
           "DnP-Firewall":['Powered by DnP Firewall'],
           "DotCMS":["/dotAsset/"],
           "Epson-Printer":["EpsonNet"],
           "EverFocus-CCTV":['<!--mei20071101 input type="image" name="recMode" style="visibility:hidden" src="stoprec.gif" onclick="changeRecordMode()"-->'],
           "EZCMS":['EZCMS Content Management System','Site Powered by EZCMS'],
           "Gitweb":['<meta name="generator" content="gitweb'],
           "HikVision-cameras":['Hikvision-Webs'],
           "HiveMail":['content="Hivemail'],
           "HoloCMS":["powered by HoloCMS"],
           "HP-Printer":['Digital Sender Series</title>','HP HTTP Server; HP'],
           "Huawei-Firewall":['Huawei Technologies Co','<!--Modify by wangxiangguang 2006-9-29 for'],
           "Hughes-Satellite-Router":['<frame src=/fs/dynaform/dw_logo.html scrolling=no marginheight=0 marginwidth=0 NORESIZE>'],
           "IBM-BladeCenter":["IBM BladeCenter"],
           "IBM-Cognos":['content="Licensed Material - Property of IBM Corp'],
           "IBM-Remote-Adapter":['<HTML><BODY bgcolor="#FFFFFF"><SCRIPT language="javascript1.2"> top.location = "/"; </SCRIPT> </BODY> </HTML>'],
           "ICEshop":["Powered by ICEshop"],
           "iDVR":['<title>iDVR</title>'],
           "Infinet-bCX1-Router":['Controller Configuration Options'],
           "Intellinet-IP-Camera":['<font size="4" color="#FFFFFF" face="Arial">NETWORK IP CAMERA<br>'],
           "Intoto-Router":['<td class="greytitle" nowrap><b>About Device Manager </b></td>'],
           "IPCop-Firewall":['<title>IPCop - Main page</title>'],
           "IPMATE-Router":['Welcome to IPMATE'],
           "Kibana":["<body kibana ng-class"],
           "Macs-CMS":["<title>Mac's CMS - Admin Login</title>"],
           "Magento":["Magento Commerce"],
           "McAfee-ePolicy-Orch":["ePolicy Orchestrator"],
           "Moodle":['<a title="Moodle'],
           "NetGear-Firewall":["NETGEAR Firewall"],
           "NetGear-Print-Server":["<title>NetGear Print Server Setup</title>"],
           "Nucleus CMS":['<meta name="name" content="My Nucleus CMS"'],
           "OpenCms":['content="OpenCms"'],
           "OpenWrt":['<title>OpenWrt Administrative Console</title>'],
           "ORITE-301-Camera":['ORITE Audio IP-Camera IC-301','Orite IC301'],
           "Panasonic-Network-Camera":['WJ-NT104 MAIN PAGE'],
           "Rainmail":['Rainmail is a product of :'],
           "Ruckus-Wireless-Router":['<div class="box"><img src="/images/logo_login.gif" width="173" height="52" alt="Ruckus Wireless" title="Ruckus Wireless" />'],
           "Rumba-CMS":['Powered by Rumba CMS'],
           "SonicWALL-Firewall":['SonicWALL'],
           "SonicWALL-SSL-VPN":['SonicWALL SSL-VPN Web Server'],
           "Sony-Network-Camera":['setWindowVar = window.open("/adm/file.cgi?next_file=setting.htm", "adminWin", setWinoptions);'],
           "Sophos-Email":['Sophos Email Appliance'],
           "Splunk":["<p><span>First time logging in?</span> Splunk's default credentials are </p><p>username: <span>admin</span><br />password: <span>changeme</span></p><p>If you've forgotten your username or password, please contact your Splunk administrator.</p>"],
           "Symfony":['Powered by <a href="http://www.symfony-project.org/">'],
           "Toshiba-Cable-Modem":["Toshiba Cable Modem"],
           "Toshiba-Network-Camera":['<title>TOSHIBA Network Camera - User Login</title>'],
           "Toshiba-Printer":['"clsTitle1">TopAccess'],
           "TP-Link-Router":['Operating System Error Nr:3997698: HTM <P><HR><H2>Access denied</H2>'],
           "VisionGS-Webcam":['<title>VisionGS Webcam Software</title>'],
           "VMware-ESXi-Server":['<script type="text/javascript">document.write("<title>" + ID_EESX_Welcome + "</title>");</script>'],
           "VMware-VirtualCenter":['<script type="text/javascript">document.write("<title>" + ID_VC_Welcome + "</title>");</script>'],
           "VMware-Zimbra":['Zimbra Web Client Log In'],
           "VoIP-Router-Gateway":['<area shape="poly" coords="152,237,152,180,194,180,260,215,293,214,293,236" href="enFrame.htm" alt="english version" onClick="form_submit'],
           "WebEye-Network-Camera":['<title>WebEye User Login</title>'],
		   "WebSVN":['<link rel="alternate" type="application/rss+xml" title="WebSVN RSS" href="rss.php?repname='],
           
           },
    # Web开发框架，info字段,html字段
    "frame":{"Nodejs Express":["X-Powered-By: Express"],
             "Parallels Plesk httpd":["X-Powered-By: PleskLin"],
             "AngularJS":["/angularjs/"],
             "CakePHP":["CAKEPHP="],
             "ThinkPHP":["X-Powered-By: ThinkPHP"],
             "django":["csrfmiddlewaretoken"],
             "ASP.NET":['vti_title:SR|Web Settings for Active Server Pages'],
             "Ruby-on-Rails":['<h3><a href="rails/info/properties" onclick="about(); return false">About your application'],
             "Spring-Framework":['org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE='],
             },
    # # 服务端语言
    # "program":{"PHP":[],
    #            "JSP":["Apache-Coyote"]},
    # Web容器,info字段
    "container":{"ComsenzEXP":["comsenz/0.0.0"],
                 "Apache":["Apache"],
                 "Tomcat":["Apache Tomcat"],
                 "Apache Tomcat/Coyote JSP":["Apache-Coyote"],
                 "Caucho Resin JSP engine":["Resin"],
                 "Oracle GlassFish":["GlassFish Server","X-Powered-By: JSP"],
                 "Oracle WebLogic Server":["X-Powered-By: Servlet"],
                 "Oracle Application Server httpd":["Oracle Application Server Containers"],
                 "Nginx":["nginx","cloudflare-nginx"],
                 "IIS":["Microsoft-IIS"],
                 "LiteSpeed httpd":["LiteSpeed"],
                 "FastCGI":["FastCGI"],
                 "thttpd":["thttpd"],
                 "OpenResty web app server":["openresty"],
                 "TornadoServer":["TornadoServer"],
                 "Jetty":["Jetty"],
                 "JBoss":["JBoss"],
                 "IBM WebSphere":["Snoop Servlet"]},
    # 操作系统，info字段
    "os":{"Debian":["(Debian)"],
          "Ubuntu":["(Ubuntu)"],
          "CentOS":["(CentOS)"],
          "Unix":["(Unix)"],
          "FreeBSD":["(FreeBSD)"],
          "Windows":["(win32)"]}
}